### ISSUE TITLE
For frame [go1_gazebo/laser_link]: Frame [go1_gazebo/laser_link] does not exist

### ISSUE THREAD

**Issue by Pelliz1997** [macc-n/ros_unitree#1]
In slam.rviz on LaserScan 
Status: Error Transform [sender=unknown_publisher]
For frame [go1_gazebo/laser_link]: Frame [go1_gazebo/laser_link] does not exist

**Comment by macc-n** [comment]
Can you provide more information? Which commands do you run to get this error?

**Comment by Pelliz1997** [comment]
I run "roslaunch unitree_navigation slam.launch rname:=go1 rviz:=true algorithm:=gmapping" and on the RViz window I got this status error regarding the LaserScan... seems like laser frame doesn't exist in fact I don't see the map... laser plugin doesn't work I think

**Comment by macc-n** [comment]
I can't reproduce the issue, I just cloned the repository on another machine, launched the slam.launch file, and everything works fine.
Have you followed all the steps?
1. Start the simulation:
`roslaunch unitree_gazebo robot_simulation.launch rname:=go1 wname:=office_small rviz:=false`
2. Start the controller:
`rosrun unitree_guide junior_ctrl`
3. Start the mapping:
`roslaunch unitree_navigation slam.launch rname:=go1 rviz:=true algorithm:=gmapping`

If you followed all the steps, which version of ROS and Gazebo are you using? What is the output of the command `rosrun rqt_tf_tree rqt_tf_tree`?

**Comment by Pelliz1997** [comment]
I'm using ROS melodic and Gazebo 9, in the frame graph I see the "laser_link"... however in the RViz seems like it doesn't exist :/ I don't know why

**Comment by macc-n** [comment]
Ok, maybe the problem is the version of ROS and/or Gazebo. I developed and tested the repository only on ROS Noetic.
If you can, switch to this version. Maybe there is a compatibility problem with the plugin libgazebo_ros_laser.so.
