### ISSUE TITLE
Does this simulation is working in real time?

### ISSUE THREAD

**Issue by abizovnuralem** [macc-n/ros_unitree#3]
Hello Dear Author, thanks for the great repo! It works fine via docker but I have laggy updates in Gazebo. The CPU goes to 70-80%. Can you give me some advice how to fix that? thanks

**Comment by macc-n** [comment]
Hi, unfortunately the controller is very CPU-consuming. The last commit helps to improve the controller performance. Have you tried to follow the instruction to change the priority?

**Comment by abizovnuralem** [comment]
Thanks for your response! I am working on port your repo into my ros2 sdk, Have you tried it before or know some solutions?

**Comment by macc-n** [comment]
I've been trying to figure out how to port it to ROS2, there are a few changes to make but I don't have much time to work on them. As far as I know, no similar solutions exist because GO1 runs ROS1. If we are working on the same projects, we might try to find a way to collaborate

**Comment by abizovnuralem** [comment]
How Can I reach you? I didnt find any contact information.
